config/routes.rb
Rails.application.routes.draw do

  resources :foods
  devise_for :users
  resources :users
  resources :inventoris
  get 'inventory_foods/:id/new', to: 'inventory_foods#new'
  delete 'inventory_foods/:id/destroy/:food_id', to: 'inventory_foods#destroy'
  post 'inventory_foods/:id/create', to: 'inventory_foods#create'
  root 'users#index'

  get 'recipe_foods/:id/new', to: 'recipe_foods#new'
  delete 'recipe_foods/:id/destroy/:food_id', to: 'recipe_foods#destroy'
  post 'recipe_foods/:id/create', to: 'recipe_foods#create'
  get '/public_recipes', to: 'recipes#public_recipes'
  resources :recipes, only: [:index, :show, :destroy, :new, :create] do
    resources :recipe_foods, only: [:index, :edit, :destroy]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/inventori.rb
class Inventori < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy, foreign_key: 'inventory_id'
end

app/controllers/inventoris_controller.rb
class InventorisController < ApplicationController
  before_action :set_inventori, only: %i[show edit update destroy]

  # GET /inventoris or /inventoris.json
  def index
    @inventoris = current_user.inventoris
  end

  # GET /inventoris/1 or /inventoris/1.json
  def show
    @foods = @inventori.inventory_foods.includes(:food)
  end

  # GET /inventoris/new
  def new
    @inventori = Inventori.new
  end

  # GET /inventoris/1/edit
  def edit; end

  # POST /inventoris or /inventoris.json
  def create
    @user = current_user
    @inventori = Inventori.new(inventori_params)
    @inventori.user = @user

    respond_to do |format|
      if @inventori.save
        format.html { redirect_to inventori_url(@inventori), notice: 'Inventori was successfully created.' }
        format.json { render :show, status: :created, location: @inventori }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventori.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventoris/1 or /inventoris/1.json
  def update
    respond_to do |format|
      if @inventori.update(inventori_params)
        format.html { redirect_to inventori_url(@inventori), notice: 'Inventori was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventori }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventori.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventoris/1 or /inventoris/1.json
  def destroy
    @inventori.destroy

    respond_to do |format|
      format.html { redirect_to inventoris_url, notice: 'Inventori was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inventori
    @inventori = Inventori.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inventori_params
    params.require(:inventori).permit(:name, :description)
  end
end

app/helpers/inventoris_helper.rb
module InventorisHelper
end

app/views/inventoris/_form.html.erb
<%= form_with(model: inventori) do |form| %>
  <% if inventori.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventori.errors.count, "error") %> prohibited this inventori from being saved:</h2>

      <ul>
        <% inventori.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label"  %>
    <%= form.text_field :name, class: "form-control m-2 w-50" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "form-label"  %>
    <%= form.text_area :description, class: "form-control m-2 w-50 row-5" %>
  </div>

  <div class="mt-4 actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/inventoris/_inventori.html.erb
<div id="<%= dom_id inventori %>">
  <p>
    <strong>Name:</strong>
    <%= inventori.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= inventori.description %>
  </p>

</div>

app/views/inventoris/_listed_inventori.html.erb
<div class="container-lg row p-4 border border-secondary rounded shadow">
  <div class="col-3">
    <h3>
      <%= link_to inventori.name, inventori , class: "nav-link text-info"%>
    </h3>
    <div><%= link_to 'Remove',
      inventori_path(inventori), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    },
      class: "btn btn-danger" %></div>
  </div>
  <div class="col-5 text-truncate">
    <%= inventori.description %>
  </div>
</div>

app/views/inventoris/edit.html.erb
<h1>Editing inventori</h1>

<%= render "form", inventori: @inventori %>

<br>

<div>
  <%= link_to "Show this inventori", @inventori %> |
  <%= link_to "Back to inventoris", inventoris_path %>
</div>

app/views/inventoris/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventoris</h1>

<div id="inventoris" class="d-flex flex-column align-items-center gap-3">
  <div class="container-lg align-self-start"><%= link_to "New Inventori", new_inventori_path, class: 'btn btn-primary' %></div>
  <% if @inventoris.count > 0 %>
    <% @inventoris.each do |inventori| %>
      <%= render 'listed_inventori', inventori: %>
    <% end %>
  <% else %>
    <h3>No Inventories posted</h3>
  <% end %>
</div>

app/views/inventoris/new.html.erb
<h1>New Inventori</h1>

<%= render "form", inventori: @inventori %>

<br>

<div>
  <%= link_to "Back to inventoris", inventoris_path %>
</div>

app/views/inventoris/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventori %>

<div>
  <%= link_to "Edit this inventori", edit_inventori_path(@inventori) , class: "btn btn-info"%> |
  <%= link_to "Back to inventoris", inventoris_path , class: "btn btn-primary"%>
</div>

<h1><%= @inventori.name %></h1>
<%= link_to 'Add food', "/inventory_foods/#{@inventori.id}/new", class: 'btn btn-primary'%>

<div>
    <table class="table table-striped table-bordered w-100 mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% if @foods.count == 0%>
      <tr class="alert alert-warning">
        <td colspan="3" class="text-center">No foods in this inventory</td>
      </tr>      
    <% else %>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= button_to 'Delete', "/inventory_foods/#{@inventori.id}/destroy/#{food.id}", method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>