config/routes.rb
Rails.application.routes.draw do

  resources :foods
  devise_for :users
  resources :users
  resources :inventoris
  get 'inventory_foods/:id/new', to: 'inventory_foods#new'
  delete 'inventory_foods/:id/destroy/:food_id', to: 'inventory_foods#destroy'
  post 'inventory_foods/:id/create', to: 'inventory_foods#create'
  root 'users#index'

  get 'recipe_foods/:id/new', to: 'recipe_foods#new'
  delete 'recipe_foods/:id/destroy/:food_id', to: 'recipe_foods#destroy'
  post 'recipe_foods/:id/create', to: 'recipe_foods#create'
  get '/public_recipes', to: 'recipes#public_recipes'
  resources :recipes, only: [:index, :show, :destroy, :new, :create] do
    resources :recipe_foods, only: [:index, :edit, :destroy]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :preparation_time, :cooking_time, :description, presence: true

  def total_cost
    total = 0
    recipe_foods.includes(:food).each do |recipe_food|
      total += recipe_food.quantity * recipe_food.food.price
    end
    total.round(2)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe
      .where(user: current_user)
      .order(created_at: :desc)
  end

  def new
    @recipe = Recipe.new
  end

  def public_recipes
    @recipes = Recipe.includes(:user).select(&:public)
  end

  def create
    @recipe = Recipe.new(create_params)

    if @recipe.save
      redirect_to(recipes_path, notice: 'Recipe created successfully!')
    else
      render(:new, status: :unprocessable_entity, alert: @recipe.errors)
    end
  end

  def show
    @recipe, = Recipe.where(id: params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def destroy
    @recipe, = Recipe.where(id: params[:id], user: current_user)
    @recipe&.destroy
    redirect_to recipes_path, notice: 'Recipe deleted!'
  end

  private

  def create_params
    params
      .require(:recipe)
      .permit(:name, :preparation_time, :cooking_time, :description, :public)
      .merge(user: current_user)
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
  def recipe_cost(recipe)
    Food
      .joins(:recipe_foods)
      .where("recipe_foods.recipe_id = #{recipe.id}")
      .sum(:price)
  end
end

app/views/recipes/_card.html.erb
<div class="card mb-3" style="width: 50rem;">
  <div class="card-body d-flex space-between">
    <h3>
      <%= link_to(recipe.name, recipe_path(recipe)) %>
    </h3>
    <div class="card-body d-flex flex-column">
      <p class="mt-4 m-0"><%= recipe.description %></p>
    </div>
  </div>
    <%= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger m-3 ms-4" %>
</div>

app/views/recipes/_public_recipe.html.erb
<div class="container-lg row p-4 border border-secondary rounded shadow">
  <div class="col-3">
    <h3><%= link_to recipe.name, recipe %></h3>
    <h4><%= "By #{recipe.user.name}" %></h4>
      <%= link_to 'Remove',
        recipe_path(recipe), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      },
        class: "btn btn-danger" %>
  </div>
  <div class="d-flex flex-column col-5 gap-2 align-items-center">
    <div class="fs-4">Total food items: <%= recipe.recipe_foods.count %></div>
    <div class="fs-4">Total Price: <%= number_to_currency(recipe.total_cost) %></div>
  </div>
</div>

app/views/recipes/index.html.erb
<section class="d-flex flex-column align-items-center">
  <h1 class="text-center mb-5">Recipes</h1>
<%= link_to "Create new Recipe", new_recipe_path, class: 'btn btn-sm btn-primary mb-2 align-self-center' %>
  <div class="d-flex flex-column">
    <% if @recipes.empty? %>
      <h2 class="text-center">The list is empty.</h2>
    <% else %>
      <% @recipes.each do |recipe| %>
      <%= render('card', recipe:)  %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/recipes/new.html.erb
<div class="container-fluid w-50 d-flex flex-column align-items-center">

  <%= form_with model: @recipe, :html => {:class => "w-50 mt-4"}, scope: :recipe do |form| %>
    <div>
      <%= form.label :name, class: "form-label" %><br>
      <%= form.text_field :name,  class:"form-control", placeholder: "Name" %>
    </div>

    <div>
      <%= form.label :preparation_time, class:"form-label" %><br>
      <%= form.text_field :preparation_time, class:"form-control", placeholder: "Preparation Time" %>
    </div>

    <div>
      <%= form.label :cooking_time , class:"form-label"%><br>
      <%= form.text_field :cooking_time ,  class:"form-control", placeholder: "Cooking Time" %>
    </div>

    <div>
      <%= form.label :description , class:"form-label"%><br>
      <%= form.text_area :description , class:"form-control", placeholder: "description" %>
    </div>

    <div class="form-check form-switch">
    <%= form.check_box :public, class: "form-check-input", role: "switch" %>
    <%= form.label :public, style: "display: block", class: "form-check-label"  %>
  </div>


    <div>
      <%= form.submit 'Create Recipe', class: "btn btn-primary my-3"  %>
    </div>
  <% end %>

</div>

app/views/recipes/public_recipes.html.erb
<p style="color: green"><%= notice %></p>

<h1>Public Recipes</h1>

<div id="recipes" class="d-flex flex-column align-items-center gap-3">
  <div class="container-lg align-self-start">
      <%= link_to 'Create new recipe', new_recipe_path, class: 'btn btn-primary' %>
  </div>
  <% if @recipes.count > 0 %>
    <% @recipes.each do |recipe| %>
      <%= render 'public_recipe', recipe: %>
    <% end %>
  <% else %>
    <h3>No public recipes posted</h3>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/recipe_show', recipe: @recipe %>