config/routes.rb
Rails.application.routes.draw do

  resources :foods
  devise_for :users
  resources :users
  resources :inventoris
  get 'inventory_foods/:id/new', to: 'inventory_foods#new'
  delete 'inventory_foods/:id/destroy/:food_id', to: 'inventory_foods#destroy'
  post 'inventory_foods/:id/create', to: 'inventory_foods#create'
  root 'users#index'

  get 'recipe_foods/:id/new', to: 'recipe_foods#new'
  delete 'recipe_foods/:id/destroy/:food_id', to: 'recipe_foods#destroy'
  post 'recipe_foods/:id/create', to: 'recipe_foods#create'
  get '/public_recipes', to: 'recipes#public_recipes'
  resources :recipes, only: [:index, :show, :destroy, :new, :create] do
    resources :recipe_foods, only: [:index, :edit, :destroy]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
 <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
  
  <%= link_to "Recipe App" , root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav">
       <% if user_signed_in? %>
       <li class="nav-item">
            <%= link_to "Foods" , foods_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Inventories" , inventoris_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My recipes" , recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Public recipes" , public_recipes_path, class: "nav-link" %>
          </li>
         <%end%>
      </ul>
      
       <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
      
         <li class="nav-item">
          <%= button_to "Sign Out" , destroy_user_session_path, method: :delete, data: { turbo: false } , class: "btn btn-warning"%>
         </li>
         <li class="nav-item">Logged in as <strong><%= current_user.email %></strong>
         <li class="nav-item">
          <%= link_to "Edit Profile" , edit_user_registration_path , class: "nav-link" %>
         </li>
      <%else%>
         <li class="nav-item">
          <%= link_to "Sign Up" , new_user_registration_path, class: "nav-link"%>
         </li>
         <li class="nav-item">
          <%= link_to "Sign In" , new_user_session_path , class: "nav-link" %>
         </li>
      
      <%end%>
       </ul>
  </div>
</nav>

app/views/shared/_recipe_show.html.erb
<section class="container" id="<%= dom_id recipe %>" >
  <h1 class="text-center mb-5"><%= recipe.name %></h1>
<span class="badge badge-primary">Private</span>
  <div class="recipe-info d-flex justify-content-around">
    <div>
      <h5>Preparation time: <%= recipe.preparation_time %></h5>
      <h5>Cooking time: <%= recipe.cooking_time %></h5>
      <div>
        <h3 class="mt-5">Description</h3>
        <p><%= recipe.description %></p>
      </div>
    </div>
    <div class="form-check form-switch">
        <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDisabled" <%= 'checked' if recipe.public %> disabled>
        <label class="form-check-label" for="flexSwitchCheckDisabled">Public</label>
      </div>
  </div>
  <div class="mt-5 d-flex justify-content-around">
    <%= link_to 'Add food', new_food_path, class: 'btn btn-primary'%>
    <%= link_to 'Add ingredient', "/recipe_foods/#{@recipe.id}/new", class: 'btn btn-primary'%>
  </div>

<div>
    <table class="table table-striped table-bordered w-100 mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @recipe_foods.each do |food| %>
        <tr>
          <td><%= food.food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= button_to 'Delete', "/recipe_foods/#{@recipe.id}/destroy/#{food.id}", method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</section>